// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHwvsQYFMBE0MdJAkwbenQlDklH50gLEM',
    appId: '1:378915104399:web:1a59df93675fc12a6332fa',
    messagingSenderId: '378915104399',
    projectId: 'milkandgroceriesapp',
    authDomain: 'milkandgroceriesapp.firebaseapp.com',
    databaseURL: 'https://milkandgroceriesapp-default-rtdb.firebaseio.com',
    storageBucket: 'milkandgroceriesapp.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEeodCAGkSx_KesS-unIDS5WMk_gqMjq4',
    appId: '1:378915104399:android:eddb0b1cd9795c0c6332fa',
    messagingSenderId: '378915104399',
    projectId: 'milkandgroceriesapp',
    databaseURL: 'https://milkandgroceriesapp-default-rtdb.firebaseio.com',
    storageBucket: 'milkandgroceriesapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXpK5p-8rjk06lW4UXE1ZT-aTXGfvHLw8',
    appId: '1:378915104399:ios:93a7df00f0d7429b6332fa',
    messagingSenderId: '378915104399',
    projectId: 'milkandgroceriesapp',
    databaseURL: 'https://milkandgroceriesapp-default-rtdb.firebaseio.com',
    storageBucket: 'milkandgroceriesapp.appspot.com',
    androidClientId: '378915104399-6gs2aq38jnrk0bb19rie4kaniisb46gd.apps.googleusercontent.com',
    iosClientId: '378915104399-hgr5cb09l6i8jbvg1pettthags5pc4pm.apps.googleusercontent.com',
    iosBundleId: 'com.example.a2Natural',
  );
}
